In [2]:
%matplotlib inline

# 파이토치

### - 파이썬 기반의 과학 연산 패키지로, 다음과 같은 두 집단을 대상으로 한다

- 넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Tensor는 넘파이의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능하다

In [3]:
from __future__ import print_function
import torch

torch.__version__

'1.12.0'

초기화 되지 않은 5X3 행렬 생성

In [5]:
x = torch.empty(5,3) # empty: 주어진 크기의 아무값으로도 초기화 되지 않은 행렬을 만든다.
print(x)

tensor([[8.9082e-39, 8.4489e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 9.6429e-39]])


무작위로 초기화된 행렬 생성

In [7]:
x = torch.randn(5,3) #표준정규분포에서 샘플링
print(x)
x = torch.rand(5,3) #0에서 1사이의 값
print(x) 

tensor([[ 0.5363,  0.9238, -0.3825],
        [-0.6361,  0.6469,  0.2539],
        [-1.7714, -2.2074, -0.2647],
        [ 0.3151, -0.4068, -1.0721],
        [-1.0829, -0.4313,  1.5984]])
tensor([[0.7040, 0.1925, 0.9610],
        [0.5229, 0.8682, 0.4386],
        [0.6393, 0.3721, 0.4975],
        [0.3843, 0.8387, 0.7109],
        [0.6475, 0.3094, 0.1169]])


dtype이 long이고 0으로 채워진 행렬 생성

In [8]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


dtype이 long이고 1로 채워진 행렬 생성

In [9]:
x = torch.ones(5,3,dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성

In [10]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만들 수 있음.
이 메소드들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(dtype)을 재사용함

In [12]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float) # torch.rand_like(tensor, dtype=~~): 파라미터로 들어간 tensor 객체의 사이즈와 똑같은 행렬을 반환, 요소들은 정규분포 그래프 상의 랜덤한 값으로 초기화되어있음.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0164,  0.9076, -0.0872],
        [-0.0461, -0.6181,  0.6720],
        [ 1.3140,  0.9666, -1.4907],
        [-0.1990,  0.3570, -0.1000],
        [-0.8772,  2.1490, -1.5631]])


행렬의 크기를 구하자

In [13]:
print(x.size()) 
print(x.shape)
# 둘 중 아무거나

torch.Size([5, 3])
torch.Size([5, 3])


In [14]:
# 덧셈
y = torch.rand(5,3)
print(x)
print(y)
print(x+y)

tensor([[-0.0164,  0.9076, -0.0872],
        [-0.0461, -0.6181,  0.6720],
        [ 1.3140,  0.9666, -1.4907],
        [-0.1990,  0.3570, -0.1000],
        [-0.8772,  2.1490, -1.5631]])
tensor([[0.5866, 0.7566, 0.3453],
        [0.6391, 0.3180, 0.0856],
        [0.9312, 0.4020, 0.3390],
        [0.3510, 0.4924, 0.7561],
        [0.7865, 0.5928, 0.7375]])
tensor([[ 0.5702,  1.6642,  0.2581],
        [ 0.5930, -0.3000,  0.7576],
        [ 2.2452,  1.3685, -1.1516],
        [ 0.1520,  0.8494,  0.6561],
        [-0.0907,  2.7417, -0.8256]])


In [15]:
# 덧셈 2
print(torch.add(x,y))

tensor([[ 0.5702,  1.6642,  0.2581],
        [ 0.5930, -0.3000,  0.7576],
        [ 2.2452,  1.3685, -1.1516],
        [ 0.1520,  0.8494,  0.6561],
        [-0.0907,  2.7417, -0.8256]])


In [16]:
result = torch.empty(5,3)
print(result)

torch.add(x,y, out=result) # 더한값(결과값)이 result 텐서로 들어감
print(result)

tensor([[-0.0164,  0.9076, -0.0872],
        [-0.0461, -0.6181,  0.6720],
        [ 1.3140,  0.9666, -1.4907],
        [-0.1990,  0.3570, -0.1000],
        [-0.8772,  2.1490, -1.5631]])
tensor([[ 0.5702,  1.6642,  0.2581],
        [ 0.5930, -0.3000,  0.7576],
        [ 2.2452,  1.3685, -1.1516],
        [ 0.1520,  0.8494,  0.6561],
        [-0.0907,  2.7417, -0.8256]])


In [17]:
# 덧셈 바꿔치기
print(y)
y.add_(x) # 바꿔치기 방식으로 tensor 값을 변경하는 연산은 _를 접미사로 갖는다.
print(y)

tensor([[0.5866, 0.7566, 0.3453],
        [0.6391, 0.3180, 0.0856],
        [0.9312, 0.4020, 0.3390],
        [0.3510, 0.4924, 0.7561],
        [0.7865, 0.5928, 0.7375]])
tensor([[ 0.5702,  1.6642,  0.2581],
        [ 0.5930, -0.3000,  0.7576],
        [ 2.2452,  1.3685, -1.1516],
        [ 0.1520,  0.8494,  0.6561],
        [-0.0907,  2.7417, -0.8256]])


tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용한다

In [18]:

x = torch.randn(4,4)
print(x)

y = x.view(16) # 16개의 차원을 가지는 벡터의 형태로 늘린다.
z = y.view(-1,2) # -1: 남는 원소를 자동으로 차원을 결정해서 넣어주어라. 2: 원소의 개수가 16개이므로 두 개씩 8개가 자동으로 들어감.(8,2)
print(y)
print(z)
print(y.size(), z.size())

tensor([[-0.9463, -1.1457,  2.8078, -1.7477],
        [ 1.0347,  1.2281, -0.7785, -0.6267],
        [-0.3043,  0.4715,  0.9932, -0.8581],
        [ 0.0873, -1.4072, -1.7428, -0.8393]])
tensor([-0.9463, -1.1457,  2.8078, -1.7477,  1.0347,  1.2281, -0.7785, -0.6267,
        -0.3043,  0.4715,  0.9932, -0.8581,  0.0873, -1.4072, -1.7428, -0.8393])
tensor([[-0.9463, -1.1457],
        [ 2.8078, -1.7477],
        [ 1.0347,  1.2281],
        [-0.7785, -0.6267],
        [-0.3043,  0.4715],
        [ 0.9932, -0.8581],
        [ 0.0873, -1.4072],
        [-1.7428, -0.8393]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item()을 사용하면 숫자값을 얻을 수 있다. 

In [19]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item()) # 숫자값 얻음

tensor([-0.3401])
<class 'torch.Tensor'> <class 'float'>
-0.3401394486427307


파이토치 홈페이지에 전치, 인덱싱, 슬라이싱 등의 연산이 나와있으니 필요할 때 찾아볼것

넘파이 변환
- Torch Tensor를 넘파이 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽다.
- Torch Tensor와 넘파이 배열은 하나를 변경하면 다른 하나도 변경됨

In [20]:
# Torch Tensor -> 넘파이배열
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy() # 넘파이 배열로 변환
print(b)

[1. 1. 1. 1. 1.]


.to 메서드를 사용해 Tensor를 어떠한 장치로도 옮길 수 있음

In [ ]:
......
device = "cuda:0"
x = x.to(device)
....

In [23]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4848 sha256=95d0231541ba31c5f6032de6fdd3549ae8e87fc87e4de297f4485434b38e5078
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor


In [24]:
import tensorflow as tf

변수 생성

In [ ]:
tf.Variable(~~~~)

텐서플로 그래프에서 tf.Variable의 값을 사용하려면 이를 단순히 tf.Tensor로 취급하면 됨

In [25]:
v = tf.Variable(0,0) # v 생성
print(v)

w = v+1 # w는 v값 기준으로 계산되는 tf.Tensor 이다. 변수가 수식에 사용될 때(여기서는 v+1), 변수는 자동적으로 tf.Tensor로 변환되어 값을 표현한다. 

print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>
tf.Tensor(1, shape=(), dtype=int32)


In [26]:
# 값을 변수에 할당하려면 assign, assign_add 메소드 활용
a = tf.Variable(0,0)
a.assign_add(1)
a.read_value()

<tf.Tensor: shape=(), dtype=int32, numpy=1>

tf.Tensor 객체의 랭크는 그 차원의 수

- 랭크 0 : 값 자체
- 랭크 1 : 벡터
- 고차원 랭크: 랭크2는 최소 한 개 이상의 열과 행으로 구성된다.
- tf.rank(객체): 객체의 랭크 구하기

 

In [27]:
# tf.Tensor 객체 형태 얻기 -> 객체.shape 사용


In [28]:
# tf.Tensor 형태 변경 =>  파이토치의 view와 굉장히 유사함. 참조할 것.